// export const query = "http://78.29.34.68:8888/object/"
export const query = "/object/"
// export const queryIcons = "http://78.29.34.68:8888/config/type/"
export const queryIconsType = "/config/type/"
export const queryIconsState = "/config/state/"
export const search = "/object/find"
export const configPath = "/config/"